![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [ ]:
import numpy as np
my_array = np.arange(0,10)

print(my_array)

print(my_array[9:0:-2]) #el - hace q vaya hacia atras y el 2 el salto

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [10]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [12]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [17]:
matrix_4 = np.arange(1,21).reshape(4,5)

print(matrix_4)

matriz_t = np.transpose(matrix_4)
print(matriz_t)

matriz_i = matrix_4[::-1,::-1]
print(matriz_i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [20]:
array_5 = matrix_4[:2,:2]

print(array_5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
array_6 = matrix_4[:3:2,0:5:2]
print(array_5)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [25]:
array_7 = matrix_4[0:3,::-1]
print(array_7) 

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [26]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:


# Método 1:  Bool (Mask)
mask = x == "Loro"
resultado_1 = x[mask]
print("1:", resultado_1)

# Método 2:  np.where()
where_2 = np.where(x == "Loro")
resultado_2 = x[where_2]
print("2:", resultado_2)


1: ['Loro' 'Loro']
2: ['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [35]:
np.random.randint(1,1000, size =20).reshape(2, 5,2)

array([[[110, 642],
        [298, 272],
        [185, 369],
        [486, 177],
        [377, 637]],

       [[815,  83],
        [991, 924],
        [980, 312],
        [777, 802],
        [644, 500]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [38]:
array_10 = matrix_4[::-1,::-1]
print(array_10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [42]:
array_11 = np.zeros(10)
array_11[3] = 1
print(array_11)



[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [43]:
vector_12 = np.arange(10,50)
print(vector_12)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [55]:
import numpy as np

array_13 = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(array_13)[0]

print(list(indices)) 


[np.int64(0), np.int64(1), np.int64(4)]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [52]:
array_14 = np.random.randn(10,10)

print(array_14)
value_min= array_14.min()
value_max= array_14.max()

print(value_min)
print(value_max)

[[-8.35632107e-01 -7.72016845e-01  1.20324216e-01 -4.73518481e-01
   1.06081615e+00 -1.01892959e+00 -5.41593872e-01  5.73125735e-01
   1.92665572e+00  9.58063623e-01]
 [-1.86832764e-02 -1.38827974e+00  4.16158868e-01 -6.91131144e-01
  -2.48104026e-01  1.49401111e-01 -7.41118051e-01 -9.51347109e-01
  -5.02356466e-01 -6.43088753e-01]
 [-3.84062091e-01 -1.90057720e-02 -1.41160839e+00  2.43321590e-01
  -5.78911244e-01 -1.58960123e+00 -9.83831751e-02  1.67304474e+00
   1.60240866e+00 -4.06378930e-01]
 [-5.65680345e-01 -1.15072061e+00 -9.16505925e-01  1.66453210e+00
   1.93634066e-01  3.84818481e-01 -1.40368579e+00 -2.11444121e+00
  -2.32336903e-01  3.57944246e-01]
 [ 2.35838651e-01 -6.21601011e-01  1.42726545e+00 -1.31176156e-01
   6.77391683e-01 -2.34427610e-01  2.63433273e-01  8.95226892e-01
   2.25036670e+00 -2.10805628e-01]
 [ 5.26713421e-01 -2.50443065e+00  1.41147978e-02  6.51007631e-01
  -6.86515617e-01 -4.31762831e-01 -2.21089050e-01  1.21238875e+00
  -4.15277135e-01  5.93574593e-01

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:

ejer_15 = np.random.rand(30)

print(ejer_15)

print("Media:", np.mean(ejer_15))


[0.48183977 0.24715426 0.85469129 0.38371165 0.53856679 0.20671217
 0.82495719 0.14664326 0.3643753  0.09649821 0.23260103 0.7157729
 0.37189804 0.76469758 0.44639213 0.48528861 0.038026   0.3174371
 0.95001812 0.75287486 0.13182394 0.27594048 0.05638528 0.29322821
 0.51339098 0.03731772 0.28890896 0.64343573 0.02050691 0.00644934]
Media: 0.3829181262765823


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [60]:
## DUDA


ejer_16 = np.ones((10, 10), dtype=int)

ejer_16[1:-1, 1:-1] = 0

print(ejer_16)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [64]:
ejer_17 = np.ones((8,8), dtype = int)

ejer_17[0::2, 0::2] = 0 #En las filas pares 
ejer_17[1::2, 1::2] = 0 # En las filas impares

print(ejer_17)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [65]:

ejer_18 = np.tile([[0, 1],[1, 0]], (4, 4))
print(ejer_18)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [80]:
ejer_19 = np.round(np.random.rand(5,5), 3)

mean_19 = np.round(np.mean(ejer_19),3)
print("La media es:", mean_19)
std_19 = np.round(np.std(ejer_19), 3)
print("La desviacion estandar es:", std_19)

norm_19 = np.round((ejer_19-mean_19)/std_19, 3)

print("Normalización:", norm_19)


La media es: 0.544
La desviacion estandar es: 0.253
Normalización: [[-0.166 -2.028 -0.103 -1.182  0.435]
 [ 0.466  0.166  0.791 -0.609  0.19 ]
 [ 1.557  1.352 -1.071 -1.51   1.664]
 [ 1.767 -1.281 -1.111 -0.798 -0.02 ]
 [ 0.217  0.055  0.858  0.431 -0.032]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [87]:
ejer_20_1 = np.arange(0,11)
print(ejer_20_1)

ejer_20_2 = ejer_20_1.copy()
ejer_20_2[3:9] = -1
print(ejer_20_2)

ejer_20_3 = ejer_20_2.copy()
ejer_20_3 = ejer_20_2[ejer_20_2 != -1]

print(ejer_20_3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')