![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [6]:
import numpy as np
print(np.__version__) 



2.5.3


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [32]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True




In [33]:
true_3x3 = np.full((3,3), True)
print(true_3x3)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [34]:
print("Tenemos este vector:", my_array)
mask = (my_array%2 !=0)
print("\nCreamos una mask q nos devuelve esta matriz de booleanos:")
print(mask)

print("\nLos impares extraídos:")
print(my_array[mask], my_array.dtype)


Tenemos este vector: [0 1 2 3 4 5 6 7 8 9]

Creamos una mask q nos devuelve esta matriz de booleanos:
[False  True False  True False  True False  True False  True]

Los impares extraídos:
[1 3 5 7 9] int64


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [41]:
my_array[my_array%2 != 0] = -1
print(my_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [39]:
array_where = np.where(my_array%2 != 0, -1, my_array)

print(array_where)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [46]:
x2_array = my_array.reshape(2,-1)
print(my_array.size)

print(x2_array)

10
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
print(a,"\n")

b = np.repeat(1, 10).reshape(2,-1)
print(b, "\n")

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 



In [ ]:
np.concatenate([a,b], axis = 0) #concatenate solo acepta un argumento


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [52]:
a = np.arange(10).reshape(2,-1)
print(a,"\n")

b = np.repeat(1, 10).reshape(2,-1)
print(b, "\n")

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 



In [ ]:
np.concatenate([a,b], axis = 1) #concatenate solo acepta un argumento

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [62]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(arrays, /, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along an existing axis.

    .. versionadded:: 2.0
        ``numpy.concat`` added as a shorthand for ``numpy.concatenate``.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [67]:
my_array = np.arange(0,10)
print(my_array)

print(my_array[0])
print(my_array[-1])

print(my_array[1:8])

[0 1 2 3 4 5 6 7 8 9]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [69]:
my_matrix  = np.array([
    [17, 23, 3],
    [4, 51, 6],
    [7, 81, 8]
])


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [71]:
array_14 = np.arange(1,50,3)

print(array_14)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [73]:
array_15 = np.arange(-4,-1, 0.25)

print(array_15)

[-4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25 -2.   -1.75 -1.5  -1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

Pyhton no lee por si mismo las imagenes

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [ ]:
array_17 = np.random.rand(4,1).reshape(2,2)
print(array_17)

[[0.47386    0.06808472]
 [0.3827107  0.11855414]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [ ]:
import random 
import numpy as np 


np.random.seed(1234)
np.random.randint(0,10,(4,5,3)) #4 matrices de 5x3


array([[[3, 6, 5],
        [4, 8, 9],
        [1, 7, 9],
        [6, 8, 0],
        [5, 0, 9]],

       [[6, 2, 0],
        [5, 2, 6],
        [3, 7, 0],
        [9, 0, 3],
        [2, 3, 1]],

       [[3, 1, 3],
        [7, 1, 7],
        [4, 0, 5],
        [1, 5, 9],
        [9, 4, 0]],

       [[9, 8, 8],
        [6, 8, 6],
        [3, 1, 2],
        [5, 2, 5],
        [6, 7, 4]]])

In [99]:
#np.random.randint(0,10,(10,10))

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [103]:
array_19 = np.full((10,1), False).reshape(2,5)

print(array_19)

[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [108]:
x =np.random.randint(10, 20, size = (5,2,6))

In [ ]:
print("1. Tiene", np.size(x), "elementos")
print("2. Tiene", np.ndim(x), "dimensiomnes")

np.shape(x)

print("3. Cada dimension tiene 5 elementos")

1. Tiene 60 elementos
2. Tiene 3 dimensiomnes
3. Cada dimension tiene 5 elementos
